#!/usr/bin/env python3

import subprocess
import time
import sys
from tabulate import tabulate
import re

# Whitelisted Organizations
whitelisted = [
    "Facebook",
    "Apple",
    "GitHub",
    "GitLab",
    "Akamai"]

# Dictionary to map country codes to country names
country_codes = {
    "UA": "Ukraine",
    "US": "United States",
    "GB": "United Kingdom",
    "FR": "France",
    "DE": "Germany",
    "IN": "India",
    "IT": "Italy",
    "BR": "Brazil",
    "CA": "Canada",
    "RU": "Russia",
    "CN": "China",
    "JP": "Japan",
    "MX": "Mexico",
    "AU": "Australia",
    "ES": "Spain",
    "KR": "South Korea",
    "SE": "Sweden",
    "NL": "Netherlands",
    "PL": "Poland",
    "BE": "Belgium",
    "CH": "Switzerland",
    "AT": "Austria",
    "NO": "Norway",
    "DK": "Denmark",
    "FI": "Finland",
    "IE": "Ireland",
    "PT": "Portugal",
    "GR": "Greece",
    "EG": "Egypt",
    "ZA": "South Africa",
    "AR": "Argentina",
    "SG": "Singapore",
    "KR": "South Korea",
    "MY": "Malaysia",
    "PH": "Philippines",
    "TH": "Thailand",
    "ID": "Indonesia",
    "NG": "Nigeria",
    "KE": "Kenya",
    "CL": "Chile",
    "CO": "Colombia",
    "PE": "Peru",
    "VE": "Venezuela",
    "AE": "United Arab Emirates",
    "KW": "Kuwait",
    "SA": "Saudi Arabia",
    "IQ": "Iraq",
    "SY": "Syria",
    "LB": "Lebanon",
    "JO": "Jordan",
    "KW": "Kuwait",
    "QA": "Qatar",
    "OM": "Oman",
    "BH": "Bahrain",
    "PK": "Pakistan",
    "BD": "Bangladesh",
    "LK": "Sri Lanka",
    "MM": "Myanmar",
    "KH": "Cambodia",
    "NP": "Nepal",
    "BT": "Bhutan",
    "MD": "Moldova",
    "AM": "Armenia",
    "GE": "Georgia",
    "UZ": "Uzbekistan",
    "TJ": "Tajikistan",
    "KG": "Kyrgyzstan",
    "TM": "Turkmenistan",
    "AZ": "Azerbaijan",
    "MN": "Mongolia",
    "RS": "Serbia",
    "HR": "Croatia",
    "BA": "Bosnia and Herzegovina",
    "MK": "North Macedonia",
    "AL": "Albania",
    "MO": "Macau",
    "LK": "Sri Lanka",
    "TT": "Trinidad and Tobago",
    "JM": "Jamaica",
    "GT": "Guatemala",
    "HN": "Honduras",
    "CR": "Costa Rica",
    "PA": "Panama",
    "DO": "Dominican Republic",
    "CU": "Cuba",
    "HT": "Haiti",
    "JM": "Jamaica",
    "PY": "Paraguay",
    "PE": "Peru",
    "EC": "Ecuador",
    "UY": "Uruguay",
    "BOL": "Bolivia"
}

# Function to extract fields from whois output
def extract_fields(ip):
    # Perform the whois lookup using the system whois command
    try:
        whois_output = subprocess.check_output(['whois', ip], stderr=subprocess.PIPE, text=True)
        
        # Retry if the whois output is empty or has an error message
        while not whois_output.strip():
            print(f"No whois output for IP {ip}, retrying...")
            time.sleep(1)
            whois_output = subprocess.check_output(['whois', ip], stderr=subprocess.PIPE, text=True)

        if not whois_output:
            return
        
        descr_param = ""
        country_param = ""

        if "RIPE" in whois_output:
            descr_param = "descr"
            country_param = "country"
        elif "APNIC" in whois_output:
            descr_param = "descr"
            country_param = "country"
        elif "LACNIC" in whois_output:
            descr_param = "owner"
            country_param = "country"
        elif "AFRINIC" in whois_output:
            descr_param = "descr"
            country_param = "country"
        elif "ARIN" in whois_output:
            descr_param = "orgname"
            country_param = "country"
        else:
            descr_param = "orgname"
            country_param = "country"

        descr_done = False
        country_done = False

        descr = ""
        country = ""
        check = f"https://abuseipdb.com/check/{ip}\nhttps://virustotal.com/gui/ip-address/{ip}"

        # Extract the required fields
        for line in whois_output.splitlines():
            if descr_param in line.lower() and not descr_done:
                descr = line.split(':', 1)[1].strip()
                if descr:
                    descr_done = True
                    for whitelisted_org in whitelisted:
                        if whitelisted_org.lower() in descr.lower():
                            descr = f"\033[38;5;229m{descr}\033[0m"
                            check = "N/A"
                            break
            elif country_param in line.lower() and not country_done:
                country = line.split(':', 1)[1].strip()
                if country:
                    country_done = True
        if not descr_done:
            if "RIPE" in whois_output:
                descr_param = "netname"
                for line in whois_output.splitlines():
                    if descr_param in line.lower():
                        descr = line.split(':', 1)[1].strip()                        
            if not descr:
                descr = "N/A"
        if not country_done:
            country = "N/A"

        # Translate country code to country name
        country = country_codes.get(country, country)

        # Return the results as a tuple
        return (ip, f"\033[92m{descr}\033[0m", country, check)

    except subprocess.CalledProcessError as e:
        print(f"Error while fetching whois data for IP {ip}: {e}")
        return (ip, "Error", "Error", "Error")

# Function to process the wordlist file
def process_wordlist(wordlist_file):
    results = []
    # Check if the wordlist file exists
    try:
        with open(wordlist_file, 'r') as file:
            # Loop through IPs in the wordlist file
            ips = file.readlines()

            for ip in sorted(set(ips)):
                is_ip = re.findall(r"\b(?:[0-9]{1,3}\.){3}[0-9]{1,3}\b", ip)
                if not is_ip:
                    continue
                ip = ip.strip()
                result = extract_fields(ip)
                if result:
                    results.append(result)
    except FileNotFoundError:
        print(f"Wordlist file not found: {wordlist_file}")
        return

    # Display the results in a table
    headers = ["IP", "Organization", "Country", "Check IP"]
    print(tabulate(results, headers=headers, tablefmt="grid"))

# Main function
if __name__ == "__main__":
    wordlist_file = sys.argv[1]
    process_wordlist(wordlist_file)
